#ifndef MULTIBOOT_H
#define MULTIBOOT_H

#define MULTIBOOT_HEADER_MAGIC 0x1BADB002
#define MULTIBOOT_HEADER_FLAGS 0x00000003
#define MULTIBOOT_HEADER_CHECKSUM (unsigned int)(-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS))

#endif // MULTIBOOT_H